_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
max_num_timeout: 0
array_parallelism: 10
cpus_per_task: 4
timeout_min: 1440
mem_gb: 16
setup:
  - module load python/3.11 rdkit/2024.09.6 cuda/12.6
  - source ~/scratch/molbo/venv/bin/activate
