_target_: molbo.acqf_optimizer.pool.GreedySampler
sampler:
  _target_: molbo.acqf_optimizer.rgfn.RGFNPoolSampler
  q: 500
  n_iterations: 250
  train_forward_n_trajectories: 64
  train_replay_n_trajectories: 32
  compute_js_divergence: false
sampler_acquisition:
  _target_: molbo.acquisition.base.PosteriorMeanAcquisition
selector:
  _target_: molbo.acqf_optimizer.pool.ThompsonSampler
  q: 50
  max_batch_size: 256
selector_acquisition:
  _target_: molbo.acquisition.base.TSAcquisition
