defaults:
  - model: gp
  - acquisition: ei
  - oracle: synthetic/gaussian_mixture_1d
  - acqf_optimizer: continuous_maximizer
  - dataset: null
  - _self_

bo:
  n_init: 5
  n_iters: 15
  checkpoint: false
  checkpoint_freq: 100

seed: 0
n: null

run_name: "${hydra:runtime.choices.model}_${hydra:runtime.choices.acquisition}_${hydra:runtime.choices.acqf_optimizer}"

wandb:
  project: molbo
  mode: disabled
  experiment: test
